# Generated by Django 2.2.4 on 2019-09-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactive_content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profesor'),
        ),
        migrations.AddField(
            model_name='contenidointeractivo',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_content.Contenido'),
        ),
        migrations.AddField(
            model_name='contenidointeractivo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_content.Curso'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profesor'),
        ),
    ]
