# Generated by Django 2.2.4 on 2019-10-09 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_content', '0002_auto_20190929_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidointeractivo',
            options={'verbose_name': 'contenido interactivo', 'verbose_name_plural': 'contenidos interactivos'},
        ),
        migrations.RemoveField(
            model_name='contenidointeractivo',
            name='curso',
        ),
        migrations.AddField(
            model_name='contenidointeractivo',
            name='curso',
            field=models.ManyToManyField(to='interactive_content.Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='users.Profesor'),
        ),
    ]
