# Generated by Django 2.2.4 on 2019-10-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interactive_content', '0003_auto_20191008_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidointeractivo',
            name='nombre',
            field=models.CharField(default='Nombre de Ejemplo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenidointeractivo',
            name='tiene_retroalimentacion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
