# Generated by Django 2.2.4 on 2019-09-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_content', '0001_initial'),
        ('users', '0001_initial'),
        ('activities', '0002_auto_20190929_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestmultipleestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estudiante'),
        ),
        migrations.AddField(
            model_name='respuestmultipleestudiante',
            name='preguntaSeleccionMultiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Pregunta'),
        ),
        migrations.AddField(
            model_name='respuestmultiple',
            name='preguntaSeleccionMultiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Pregunta'),
        ),
        migrations.AddField(
            model_name='respuestavof',
            name='preguntaVoF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Pregunta'),
        ),
        migrations.AddField(
            model_name='respuestaestudiantevof',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estudiante'),
        ),
        migrations.AddField(
            model_name='respuestaestudiantevof',
            name='preguntaVoF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.RespuestaVoF'),
        ),
        migrations.AddField(
            model_name='respuestaabiertaestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estudiante'),
        ),
        migrations.AddField(
            model_name='respuestaabiertaestudiante',
            name='preguntaAbierta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Actividad'),
        ),
        migrations.AddField(
            model_name='marca',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='interactive_content.ContenidoInteractivo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Actividad'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Estudiante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Marca'),
        ),
    ]
