# Generated by Django 2.2.4 on 2019-10-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190929_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestmultipleestudiante',
            name='preguntaSeleccionMultiple',
        ),
        migrations.AddField(
            model_name='respuestmultipleestudiante',
            name='respuestmultiple',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.Respuestmultiple'),
            preserve_default=False,
        ),
    ]
