# Generated by Django 2.2.4 on 2019-10-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('interactive_content', '0003_auto_20191008_2213'),
        ('activities', '0004_auto_20191011_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcionmultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=200)),
                ('esCorrecta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbierta',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Actividad')),
                ('enunciado', models.CharField(max_length=200)),
            ],
            bases=('activities.actividad',),
        ),
        migrations.CreateModel(
            name='PreguntaFoV',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Actividad')),
                ('pregunta', models.CharField(max_length=200)),
                ('esVerdadero', models.BooleanField()),
            ],
            bases=('activities.actividad',),
        ),
        migrations.CreateModel(
            name='PreguntaOpcionMultiple',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Actividad')),
                ('enunciado', models.CharField(max_length=200)),
                ('esMultipleResp', models.BooleanField()),
            ],
            bases=('activities.actividad',),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('intento', models.IntegerField()),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Estudiante')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactive_content.Grupo')),
            ],
        ),
        migrations.RemoveField(
            model_name='respuestaestudiantevof',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiantevof',
            name='preguntaVoF',
        ),
        migrations.RemoveField(
            model_name='respuestmultiple',
            name='preguntaSeleccionMultiple',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='retroalimentacion',
        ),
        migrations.RemoveField(
            model_name='respuestaabiertaestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestaabiertaestudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='respuestaabiertaestudiante',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='respuestavof',
            name='esCorrecta',
        ),
        migrations.RemoveField(
            model_name='respuestavof',
            name='id',
        ),
        migrations.RemoveField(
            model_name='respuestmultipleestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestmultipleestudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='respuestmultipleestudiante',
            name='seleccionada',
        ),
        migrations.AddField(
            model_name='actividad',
            name='retroalimentacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='respuestaabiertaestudiante',
            name='retroalimentacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='respuestavof',
            name='esVerdadero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tieneRetroalimentacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='respuestaabiertaestudiante',
            name='preguntaAbierta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.PreguntaAbierta'),
        ),
        migrations.AlterField(
            model_name='respuestavof',
            name='preguntaVoF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.PreguntaFoV'),
        ),
        migrations.AlterField(
            model_name='respuestmultipleestudiante',
            name='respuestmultiple',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.Opcionmultiple'),
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='RespuestaEstudianteVoF',
        ),
        migrations.DeleteModel(
            name='Respuestmultiple',
        ),
        migrations.AddField(
            model_name='opcionmultiple',
            name='preguntaSeleccionMultiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.PreguntaOpcionMultiple'),
        ),
        migrations.AddField(
            model_name='respuestaabiertaestudiante',
            name='respuesta_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestavof',
            name='respuesta_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestmultipleestudiante',
            name='respuesta_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Respuesta'),
            preserve_default=False,
        ),
    ]
