# Generated by Django 2.2.4 on 2019-12-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_pausa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pausa',
            name='enunciado',
            field=models.CharField(max_length=1000),
        ),
    ]
