# Generated by Django 2.2.4 on 2019-12-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20191206_0740'),
        ('activities', '0009_actividad_tipoactividad'),
    ]

    operations = [
    ]
