# Generated by Django 2.2.4 on 2020-03-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_merge_20191206_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='puedeSaltar',
            field=models.BooleanField(default=False),
        ),
    ]
