# Generated by Django 2.2.4 on 2020-03-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_actividad_puedesaltar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='puedeSaltar',
        ),
    ]
